[package]
name = "fuzzy_systems"
description = "Zero-cost statically-typed low-level fuzzy systems toolbox."
version = "0.1.0"
authors = ["Misha Kotwica <udiknedormin@gmail.com>"]
edition = "2018"

[dependencies]
num = "^0.1.32" 
